app = "easychat"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "ams"

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
auto_stop_machines = "stop"
min_machines_running = 0

  [http_service.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"
